---
# Playbook that installs and configures node dependencies
# follows the official instalation guide
# https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

- name: Check if nodejs repository is installed
  stat:
    path: /etc/apt/sources.list.d/nodesource.list
  register: nodejs

# LTS until 2023-04-30
# https://nodejs.org/en/about/releases/
- name: Download nodejs 14.x setup script (LTS)
  get_url:
    url: "https://deb.nodesource.com/setup_14.x"
    dest: "/tmp/node_setup.sh"
    mode: 0700
  when: nodejs.stat.exists == False

# Since shell commands are not idempotent we manually
# check above if already have the nodejs repo (implying
# all nodejs steps were previously successful)
- name: Setup nodejs repositories
  shell: "/tmp/node_setup.sh"
  become: yes
  when: nodejs.stat.exists == False

- name: Install nodejs and dependencies
  apt:
    name: [
      'build-essential',
      'nodejs',
      ]
    state: latest
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive
