---
# Task list to intitialize a competition by adding a global scorebaords and
# optionally starting the event

# Fix Found Problems with werkzeug2.0.1 downgrading to werkzeug==0.16.1  
- name: Remove Markupsafe
  shell:
    cmd: rm -rf {{virtualenv_dir}}/lib/python3.7/site-packages/markupsafe
  become: yes

- name: Install Markupsafe==1.1.1 current
  pip:
    name: markupsafe==1.1.1
    virtualenv: "{{ virtualenv_dir }}"
    virtualenv_python: python3.7

- name: Auto Initialize CTF
  shell:
    cmd: >
      . {{virtualenv_dir}}/bin/activate;
      {{ scripts_dir }}/init-ctf.py
      -g '{{ global_scoreboard }}'
      {% if auto_start_ctf %} --start {% endif %}
  register: result
  changed_when: '"Added scoreboard" in result.stdout or "Started CTF" in result.stdout'
