---

# install both for future compatibility with ansible python3
- name: Install pip
  apt:
    name: [
#      'python-pip',
      'curl',
      'python3-pip'
      ]

- name: Curl https://bootstrap.pypa.io/pip/2.7/get-pip.py
  command: curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
  args:
    chdir: /tmp/

- name: Install pip for python2
  command: python2 get-pip.py 
  args:
    chdir: /tmp/

- name: Install cryptography (requirement for openssl_csr_module)
  pip:
    name: cryptography
