---
# Playbook that installs MongoDB and associated utilities
# TODO: Consolidate mongodb tasks into web

- name: Add apt key by id
  apt_key:
    keyserver: "{{mongodb_apt_keyserver}}"
    id: "{{mongodb_apt_key_id}}"

- name: Add repository
  apt_repository:
    repo: "{{ mongodb_repo }}"
    state: present

- name: Install mongo
  apt:
    name: [
      'mongodb-org', # from PPA
    ]
    state: present
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install redis
  apt:
    name: [
      'redis-server',
    ]
    state: present
  when: not aws_elasticache
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Ensure mongodb is running
  service:
    name: "{{ mongodb_daemon_name }}"
    state: started
    enabled: yes

- name: Ensure redis is running and started on boot
  service:
    name: redis-server
    state: started
    enabled: yes
  when: not aws_elasticache
